package com.redhat.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Shopping Cart")
public class ShoppingCart  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Cart Item Promotional Savings")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Double cartItemPromoSavings;
    
    @org.kie.api.definition.type.Label(value = "Cart Item Total")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Double cartItemTotal;
    
    @org.kie.api.definition.type.Label(value = "Shopping Cart Total")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Double cartTotal;
    
    @org.kie.api.definition.type.Label(value = "Shipping Promotional Savings")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Double shippingPromoSavings;
    
    @org.kie.api.definition.type.Label(value = "Shipping Total")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double shippingTotal;
    
    @org.kie.api.definition.type.Label(value = "List of Shopping Cart Items")
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.List<com.redhat.coolstore.ShoppingCartItem> shoppingCartItemList;

    @org.kie.api.definition.type.Label(value = "Category")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String category;

    @org.kie.api.definition.type.Label(value = "Sub Category")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String subCategory;

    public ShoppingCart() {
    }

    public ShoppingCart(java.lang.Double cartItemTotal, java.lang.Double cartItemPromoSavings, java.lang.Double shippingTotal, java.lang.Double shippingPromoSavings, java.lang.Double cartTotal, java.util.List<com.redhat.coolstore.ShoppingCartItem> shoppingCartItemList, java.lang.String category, java.lang.String subCategory) {
        this.cartItemTotal = cartItemTotal;
        this.cartItemPromoSavings = cartItemPromoSavings;
        this.shippingTotal = shippingTotal;
        this.shippingPromoSavings = shippingPromoSavings;
        this.cartTotal = cartTotal;
        this.shoppingCartItemList = shoppingCartItemList;
        this.category = category;
        this.subCategory = subCategory;
    }


    
    public java.lang.Double getCartItemPromoSavings() {
        return this.cartItemPromoSavings;
    }

    public void setCartItemPromoSavings(  java.lang.Double cartItemPromoSavings ) {
        this.cartItemPromoSavings = cartItemPromoSavings;
    }
    
    public java.lang.Double getCartItemTotal() {
        return this.cartItemTotal;
    }

    public void setCartItemTotal(  java.lang.Double cartItemTotal ) {
        this.cartItemTotal = cartItemTotal;
    }
    
    public java.lang.Double getCartTotal() {
        return this.cartTotal;
    }

    public void setCartTotal(  java.lang.Double cartTotal ) {
        this.cartTotal = cartTotal;
    }
    
    public java.lang.Double getShippingPromoSavings() {
        return this.shippingPromoSavings;
    }

    public void setShippingPromoSavings(  java.lang.Double shippingPromoSavings ) {
        this.shippingPromoSavings = shippingPromoSavings;
    }
    
    public java.lang.Double getShippingTotal() {
        return this.shippingTotal;
    }

    public void setShippingTotal(  java.lang.Double shippingTotal ) {
        this.shippingTotal = shippingTotal;
    }
    
    public java.util.List<com.redhat.coolstore.ShoppingCartItem> getShoppingCartItemList() {
        return this.shoppingCartItemList;
    }

    public void setShoppingCartItemList(  java.util.List<com.redhat.coolstore.ShoppingCartItem> shoppingCartItemList ) {
        this.shoppingCartItemList = shoppingCartItemList;
    }

    public java.lang.String getCategory() {
        return this.category;
    }

    public void setCategory( java.lang.String category ) {
        this.category = category;
    }

    public java.lang.String getSubCategory() {
        return this.subCategory;
    }

    public void setSubCategory( java.lang.String subCategory ) {
        this.subCategory = subCategory;
    }

    
}